
CREATE DATABASE  IF NOT EXISTS `bballsrc` /*!40100 DEFAULT CHARACTER SET utf8 */;
CREATE DATABASE  IF NOT EXISTS `bballtrg` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `bballsrc`;

SET NAMES utf8mb4;

-- SET FOREIGN_KEY_CHECKS = 0;
-- SET FOREIGN_KEY_CHECKS = 1;

