-- ----------------------------
--  Table structure for `Teams`
-- ----------------------------
-- DROP TABLE IF EXISTS `Teams`;
CREATE TABLE IF NOT EXISTS `Teams` (
  `yearID` int(11) NOT NULL,
  `lgID` varchar(64) NOT NULL,
  `teamID` varchar(64) NOT NULL,
  `franchID` varchar(64) NOT NULL,
  `divID` varchar(64) NOT NULL,
  `Rank` int(11) DEFAULT NULL,
  `G` int(11) DEFAULT NULL,
  `Ghome` varchar(64) DEFAULT NULL,
  `W` int(11) DEFAULT NULL,
  `L` int(11) DEFAULT NULL,
  `DivWin` varchar(64) DEFAULT NULL,
  `WCWin` varchar(64) DEFAULT NULL,
  `LgWin` varchar(64) DEFAULT NULL,
  `WSWin` varchar(64) DEFAULT NULL,
  `R` int(11) DEFAULT NULL,
  `AB` int(11) DEFAULT NULL,
  `H` int(11) DEFAULT NULL,
  `B2` int(11) DEFAULT NULL,
  `B3` int(11) DEFAULT NULL,
  `HR` int(11) DEFAULT NULL,
  `BB` int(11) DEFAULT NULL,
  `SO` int(11) DEFAULT NULL,
  `SB` int(11) DEFAULT NULL,
  `CS` varchar(64) DEFAULT NULL,
  `HBP` varchar(64) DEFAULT NULL,
  `SF` varchar(64) DEFAULT NULL,
  `RA` int(11) DEFAULT NULL,
  `ER` int(11) DEFAULT NULL,
  `ERA` float DEFAULT NULL,
  `CG` int(11) DEFAULT NULL,
  `SHO` int(11) DEFAULT NULL,
  `SV` int(11) DEFAULT NULL,
  `IPouts` int(11) DEFAULT NULL,
  `HA` int(11) DEFAULT NULL,
  `HRA` int(11) DEFAULT NULL,
  `BBA` int(11) DEFAULT NULL,
  `SOA` int(11) DEFAULT NULL,
  `E` int(11) DEFAULT NULL,
  `DP` varchar(64) DEFAULT NULL,
  `FP` float DEFAULT NULL,
  `name` varchar(64) DEFAULT NULL,
  `park` varchar(64) DEFAULT NULL,
  `attendance` varchar(64) DEFAULT NULL,
  `BPF` int(11) DEFAULT NULL,
  `PPF` int(11) DEFAULT NULL,
  `teamIDBR` varchar(64) DEFAULT NULL,
  `teamIDlahman45` varchar(64) DEFAULT NULL,
  `teamIDretro` varchar(64) DEFAULT NULL,
  PRIMARY KEY(`yearID`, `lgID`, `teamID`, `franchID`, `divID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

